### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by cchudant** [jojoe77777/SeedMiner#1]
Hello!

Where is the code? Is this open-source?

**Comment by snessim** [comment]
In literally every release including the one a single day before your "issue"...

**Comment by cchudant** [comment]
> In literally every release including the one a single day before your "issue"...

did you actually open the .zip file?

this zip file has nothing except the readme in it, it is autogenerated by github and is a snapshot of the repository

why is this program on github if it isn't opensource?

**Comment by snessim** [comment]
I didn't, apologies for my tone and ignorance.
