### ISSUE TITLE
This file is a trojan!

### ISSUE THREAD

**Issue by ygolomeg** [jojoe77777/SeedMiner#4]
![Screenshot5](https://user-images.githubusercontent.com/82951933/117866354-09282900-b265-11eb-8fd0-995d76219cd7.png)
![Screenshot_6](https://user-images.githubusercontent.com/82951933/117866380-104f3700-b265-11eb-91d3-6246593997a8.png)
I thought I trusted you @jojoe77777 
why do you need _win32sysloader.pyd on a MACRO

**Comment by jojoe77777** [comment]
read the code lol https://github.com/jojoe77777/SeedMiner/blob/main/SeedMiner.py
it uses win32 to resize the minecraft window
