### ISSUE TITLE
GUI doesn't seem right

### ISSUE THREAD

**Issue by dylancetin** [jojoe77777/SeedMiner#5]
Is it supposed to be like this?
![Ekran görüntüsü 2021-06-06 200635](https://user-images.githubusercontent.com/74064578/120933562-5af88d80-c703-11eb-8fcd-bd163f99d83f.png)

**Comment by jojoe77777** [comment]
no

**Comment by dylancetin** [comment]
oh ok make sense..

**Comment by heatvvave** [comment]
how to fix?

**Comment by AvishekN25** [comment]
I have the same issue
